FROM registry.access.redhat.com/ubi8/go-toolset AS builder
WORKDIR .
COPY . .
RUN make build

FROM scratch
COPY --from=builder /opt/app-root/src/snmp_notifier /usr/bin/
COPY description-template.tpl  /etc/snmp_notifier/description-template.tpl
EXPOSE      9464
ENTRYPOINT  ["/usr/bin/snmp_notifier"]
LABEL io.k8s.display-name="SNMP Notifier" \
      io.k8s.description="A webhook to relay Prometheus alerts as SNMP traps" \
      io.openshift.tags="snmp"